### ISSUE TITLE
[Feature Request] Show the recorded time human-readable

### ISSUE THREAD

**Issue by tai271828** [zztin/ctimer#22]
## Is your feature request related to a problem?
We have implemented the feature to record each start/end time with sqlite db https://github.com/zztin/ctimer/pull/16 At this moment the db only records the time in the second(?) format since epoch. It will help if we could store the time in human-readable format.

## Describe the solution you'd like
Directly convert before returning/storing the value.

**Comment by zztin** [comment]
Hi, This is a good point. Seconds since epoch format might be friendly for downstream data processing and visualization, however, if you have the need to view the data sheet in SQL format, do you think it can be a good idea to have another column to store the human-readable format for time? 
I am also thinking of adding one more column to store the length of the clock (sometimes it is pre-ended so < 25 mins).

However, integration of the older format and the new format needs to be taken care of.

**Comment by tai271828** [comment]
+1 to this idea : )

**Comment by zztin** [comment]
use --visual for this.
